# Generated by Django 4.1.1 on 2022-11-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_comment_id_alter_restaurant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='price',
            new_name='narxi',
        ),
    ]
