# Generated by Django 4.1.1 on 2022-11-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_rename_price_restaurant_narxi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='taste',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='vat',
        ),
    ]
