# Generated by Django 4.1.1 on 2022-11-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_restauranty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantY',
        ),
    ]
